### PR TITLE
Fix sys stats cookie being lost from UI requests

### PR DESCRIPTION
**Pull request by d2r**
Undo part of a change introduced with 7694401ddf8bc8c988dd70414f1aae8d1540e02b

This fixes a possible regression from 0.9.0 introduced in 0.9.0-rc1

### CODE REVIEW

**Comment by ptgoetz** [comment]
Added to 0.9.0 milestone.

**Comment by ptgoetz** [comment]
+1

**Comment by xumingming** [comment]
+1

**Comment by d2r** [comment]
The previous commit may only fix the issue by accident as a special case.

Cookies need to be wrapped properly so that they can be bound properly in the destructuring of the request.  I noticed this when I applied the same fix to a version of the ui running with servlet-request parameters, and in that test the :cookies were not bound correctly.

**Comment by d2r** [comment]
New patch properly wraps cookies as before.  I also verified the code reloads when the source file changes via the repl.

**Comment by ptgoetz** [comment]
Bump. Looking for more community review.

**Comment by revans2** [comment]
I am not an expert on this, but all of the compojure tutorials I have seen call compojure.handler/site on the routes.
Even the log-viewer app is doing it.  I am +1 on the change.

Full disclosure: I work with Derek

**Comment by d2r** [comment]
To clarify what happens:

compojure.handler/site -> ring.middleware.session/wrap-session -> ring.middleware.cookies/wrap-cookies

compojure.handler/site does other nice things, but wrapping the cookies is what we need to restore the functionality.  I do not think the rest of compojure.handler/site hurts anything.  Also, that is what was in core.clj before the auto-reload patch anyway.

**Comment by d2r** [comment]
Closed on accident, reopening

**Comment by anfeng** [comment]
+1

**Comment by ptgoetz** [comment]
Thanks @anfeng. Merging for rc3.

**Pull request merged**
