### PR TITLE
prevent duplicates on Fields

### PR DESCRIPTION
**Pull request by git2samus**
Fields receives a list of strings that is stored internally on an ArrayList however it is indexed with a HashMap and field indexes can be retrieved by name (Tuple fields can be retrieved by name too) therefore Fields should prevent duplicates to avoid ambiguity and internal inconsistencies between _index and _fields.

I couldn't find tests for this class so I've added those as well.

### CODE REVIEW

**Comment by nathanmarz** [comment]
This is great. Can you sign a contributor agreement so that I can merge this in? It should only take a couple minutes. Instructions here: https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by git2samus** [comment]
sent

**Comment by nathanmarz** [comment]
Merged, thanks!

**Review by MooreTattz — COMMENTED** [review]
test/clj/backtype/storm/fields_test.clj

**Pull request merged**
