### PR TITLE
Change ShellSpout and ShellBolt so that returning task IDs to the spout or bolt is optional

### PR DESCRIPTION
**Pull request by barrywhart**
After doing some profiling of a real-life topology implemented in Python, I found that a lot of time was spent communicating between ShellSpout or ShellBolt and the actual spout or bolt code in Python. After making the attached changes to ShellSpout and ShellBolt, and making a couple of changes to storm.py, the communication time was 2.5x faster.

The primary change to storm.py was adding an optional "need_task_ids" parameter to emitSpout() and emitBolt().

I followed this up by adding new storm.py functions emitManySpout() and emitManyBolt(). Using these functions to batch up the emission of tuples improved communication performance about another 25%.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Before I look at this, can you send me a contributor agreement? Instructions are on this page (should only take a few minutes): https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by barrywhart** [comment]
Ok, I just sent it.

Once you take a look at this, I'll be happy to contribute the related storm.py changes as well.

Barry

**Comment by nathanmarz** [comment]
@barrywhart This looks good. It would be great to add the storm.py updates as well.

**Comment by barrywhart** [comment]
Ok, I will create a pull request for the storm.py changes.

Thanks,
Barry

**Comment by nathanmarz** [comment]
This is now merged in. Thanks!

**Comment by barrywhart** [comment]
Now that Petrel (the Python/Storm library) has been released as open source, the updated storm.py is available in that project. I believe it is a drop-in replacement for the existing storm.py. Would you like me to submit a pull request?

**Comment by nathanmarz** [comment]
@barrywhart Absolutely

**Pull request closed without merging**
