### PR TITLE
0.8.0 better hooks

### PR DESCRIPTION
**Pull request by velvia**
Add info about the taskId that is emtting, failing, or acking tuples, and the spout taskId to which ack and fail events are sent.  This would be very useful for, say, a custom monitoring system implemented on top of the hooks.  The taskId allows all of the events to be correlated to the local worker JVM's tasks.

I didn't see any tests for hooks.

I have other ideas for extending hooks:
- Add an event for calling execute(tuple) on a bolt task
- Add hooks for starting and cleaning up a child worker
- Add documentation  :)

### CODE REVIEW

**Comment by nathanmarz** [comment]
Finally got around to this... but I need a contributor agreement before I can merge this in. Instructions are here (should take just a couple minutes): https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by velvia** [comment]
Hey Nathan,

Sent you the contributor agreement separately. 

I was thinking of adding a hook to when the bolt execute() is called as well.  Can be a separate pull I guess.

Also wondering how this will all fit in when your higher level stuff (forgot the codename - was it Tornado?) is done. 

-Evan

**Comment by nathanmarz** [comment]
This is now merged into master.

**Comment by velvia** [comment]
Nathan,

Thanks.  So is 0.8 development happening on master or just 0.8 branch?

-Evan
Carry your candle, run to the darkness
Seek out the helpless, deceived and poor
Hold out your candle for all to see it
Take your candle, and go light your world

**Comment by nathanmarz** [comment]
It's been happening on master.

**Pull request closed without merging**
