### PR TITLE
add 'contains' method to Fields and Tuple.

### PR DESCRIPTION
**Pull request by okapies**
Adds `boolean contains(String field)` method to `Fields` and `Tuple` to check whether a tuple contains a specified field or not as in 0.7.*. Please see also #317.

### CODE REVIEW

**Comment by okapies** [comment]
Hmm, I found "Contributing to Storm" page.

https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

Do I have to sign a "contributor agreement" to send this patch?

**Comment by nathanmarz** [comment]
Yes, you'll need to send me a signed contributor agreement before I can look at this or merge it in.

**Comment by okapies** [comment]
Ok. I'll read it.

I have a question.
Can I sign the agreement as an individual, not as an employee employed by my employer?

**Comment by nathanmarz** [comment]
That's fine.

**Comment by okapies** [comment]
Ok, thanks. I sent the signed agreement. Please inspect it.

**Comment by okapies** [comment]
Thanks!

**Pull request merged**
