### PR TITLE
build_release.sh  modified to avoid duplicated storm-core.jar files

### PR DESCRIPTION
**Pull request by anfeng**
Some Storm modules (ex. storm-netty) depend on storm-core. We need to modify build_release.sh so that storm-core-VERSION.jar is not packaged in storm.home and its lib subdir.

### CODE REVIEW

**Comment by xiaokang** [comment]
Hi @anfeng, is it more general to remove all $DIR/*.jar from $DIR/lib/ ? Since other jars may be copied to lib if it's a dependency of other modules.

**Comment by nathanmarz** [comment]
I agree with @xiaokang

**Comment by anfeng** [comment]
OK, it's revised per @xiaokang

**Comment by nathanmarz** [comment]
Shouldn't that be cd ../.. at the end?

**Comment by anfeng** [comment]
Nathan, I have revised the "cd ../.."

**Pull request merged**
