### PR TITLE
Shell Spout & Python Lib Spout

### PR DESCRIPTION
**Pull request by jimrubenstein**
This time...with less noise.  Sorry for all the confusion!

### CODE REVIEW

**Comment by nathanmarz** [comment]
Finally got a chance to look at this again. I'd like to get this merged in, but there are some issues. I'll just enumerate them:
1. The Python API is wrong. "ack" and "fail" methods only take the id of the tuple, not an actual tuple. Your Java and Python code seem to be inconsistent in that regard.
2. The modifications to "readMsg" are bad (the try... except). If you know you're just going to read a string (and not a json object), you should just use readStringMsg. I would recommend encoding the "next" command just like ack/fail commands by using a map ({"command": "next"}). 
3. You shouldn't assume that the "id" created by nextTuple is a Long. It can be any Object, as shown in the Java API for spouts.
4. Your Java code gets anchors from the multilang process. There's no concept of anchors in spouts. Since those anchors are unused, this seems to be a typo.

I'd like to get this finished soon, so I'll be much faster with my feedback from now on.

**Comment by jimrubenstein** [comment]
Thanks for looking over the changes, I'll work on addressing the things you mentioned and commit them to this pull request.

**Comment by tomjack** [comment]
Hey, I'm working on #85 (tentatively also ShellSpout, as I'm trying to factor out the common code). Couple questions:
- In Jim's patch, there seems to be trouble analogous to #85 (while the subprocess is not emitting tuples, it won't get any acks/fails). How does this sound: ShellSpout spawns a thread that blocks on reading the process output, loading the emitted tuples onto a queue that is polled in nextTuple with a 1ms (?) sleep.
- Nathan, you say that we should not assume the id from nextTuple is a Long. Do you mean we should just directly use any String/JSONObject/JSONArray/Long/Boolean the spout sends over?

**Comment by nathanmarz** [comment]
Thomas, yes on both. nextTuple should most definitely be non-blocking.

**Comment by jimrubenstein** [comment]
Sorry I haven't gotten back around to working on this stuff; I had to move on and take care of some other projects - I hope to get back to it at some point.  @Tomo, thanks for picking it up on this, I will absolutely want to/need to use a ShellSpout to implement the features I have coming up....damn time, there's never enough of it.

**Comment by nathanmarz** [comment]
Closing this because @tomo finished this feature in another pull request

**Pull request closed without merging**
