### PR TITLE
Allow ShellBolts to optionally specify the logging level.

### PR DESCRIPTION
**Pull request by msukmanowsky**
Default logging will still be info to support backwards compatibility.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Can you send me a contributor agreement? Instructions here: https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by msukmanowsky** [comment]
Sent!

**Comment by nathanmarz** [comment]
I'm not a fan of this implementation. Can you use numbers instead of strings for specifying the level? 0 = debug, 1 = info, etc. And it seems like it should test against info first because that's the common case.

**Comment by msukmanowsky** [comment]
Hmm, considering this is implemented in the ShellBolt, having an enum kind of implementation (0 = debug, 1 = info) means that each language would need to maintain the same kind of enum.  I thought it'd be an easier interface for the languages to specify the log level using a string no?

**Comment by nathanmarz** [comment]
Numbers are more performant. This is a protocol, it should be done efficiently.

**Comment by msukmanowsky** [comment]
Alright, think we're all set here, mind giving it a look @nathanmarz?

**Pull request closed without merging**
