### PR TITLE
Fix race condition on zeromq sockets between the threads that send tuple...

### PR DESCRIPTION
**Pull request by herberteuler**
Hi Nathan, we are facing the same issue as this one: http://groups.google.com/group/storm-user/browse_thread/thread/932da776159fd063 but we do not see java.lang.VerifyError as Dane did.

As we investigate the issue, we find that the cause of the problem is mainly due to the race condition on using and managing socket connections between the sender threads and the refresher thread.  If a worker finds that some of its downstream connections have dead, and refreshes the dead connections, the closed socket may contain NULL values and hence the crash happens.

A patch is attached.  How do you think about it?

### CODE REVIEW

**Comment by nathanmarz** [comment]
Can you explain the exact order of events that causes a crash and then explain how this fixes it? I don't see the race condition.

**Comment by herberteuler** [comment]
Okay.  The race condition happens between the senders and the refresh thread.  In the sender, we have this:

```
    (when batch-end?
      (read-locked endpoint-socket-lock
        (let [node+port->socket @node+port->socket
              task->node+port @task->node+port]
          (fast-list-iter [[task ser-tuple] drainer]
            ;; TODO: consider write a batch of tuples here to every target worker  
            ;; group by node+port, do multipart send              
            (let [node-port (get task->node+port task)]
              (when node-port
                (msg/send (get node+port->socket node-port) task ser-tuple)))))))
```

Here the set of sockets is stored in `node+port->socket' and we only dereference once before the iteration on tuples (I think this is for performance considerations).

But the dereferenced snapshot of the sockets could be changed in the refresh thread:

```
          (write-locked (:endpoint-socket-lock worker)
            (reset! (:cached-task->node+port worker)
                    (HashMap. my-assignment)))
          (doseq [endpoint remove-connections]
            (.close (get @(:cached-node+port->socket worker) endpoint)))
          (apply swap!
                 (:cached-node+port->socket worker)
                 #(HashMap. (dissoc (into {} %1) %&))
                 remove-connections)
```

There is a write lock here, but it does not protect all the operations.  In the second `doseq' form, the socket upon which`close' is invoked might be one that a sender has dereferenced during its sending phase, and the crash happens exactly when the sender tries to send with a closed socket.

There is a second change in the attached patch.  The call to `dissoc' above does not do what is expected, causing removed connections remain in the socket map.  We need an`apply' there.

**Comment by nathanmarz** [comment]
You're going to have to be more specific. What is the exact sequence of operations that leads to a crash? I want you to explain this on a line by line basis of what happens, how the socket map changes, and so on.

**Comment by herberteuler** [comment]
Let's say the sender is thread A, and the refresh mechanism is in thread B.  Here is the sequence of operations:
1. The sender thread A read-locks the worker's sockets lock and dereferences its value, gets a map containing many sockets.  Among the sockets there is a socket connected to machine M, port 6700.  A then starts sending tuples with this set of sockets.
2. During A's sending phase, the refresh thread B detects that M:6700 has dead.  It computes the new connections and connections to be removed.  Then B write-locks the worker's sockets lock, and resets it to a new map containing a new set of active sockets.  Then the write-lock is released.
3. A is still sending.
4. B then starts to close removed connections.  Now suppose M:6700 is among the sockets to be closed.  B closes it, but A is still sending.
5. Inside JZMQ, a closed socket has NULL as its 'socketHandle' field.  A tries to send tuples via this closed socket, then JZMQ's 'send' method aborts by seeing its 'socketHandle' to be NULL.

But I find the write-lock does not protect all operations too in my patch, it needs to be corrected.

**Comment by herberteuler** [comment]
I have updated the patch.  This time all operations to cached sockets and task node-port map are all protected inside the write lock, with the removal of dead sockets comes first, followed by creation of new sockets, followed by update of task node-port map.

**Comment by nathanmarz** [comment]
#2 is impossible because the entire send operation is protected by the read lock. So the write lock can't be acquired until that operation completes.

**Comment by herberteuler** [comment]
You are right, what I posted does not sound like what really happened.  I am still trying to explain the actions, but for what is worthy, here is the stack trace before crashing:

Inside refresher thread:

2012-11-20 11:47:18 STDIO [ERROR] finalize() called
2012-11-20 11:47:18 STDIO [ERROR] java.lang.Exception
2012-11-20 11:47:18 STDIO [ERROR] at org.zeromq.ZMQ$Socket.finalize(ZMQ.java:918)
2012-11-20 11:47:18 STDIO [ERROR] at org.zeromq.ZMQ$Socket.close(ZMQ.java:339)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
2012-11-20 11:47:18 STDIO [ERROR] at java.lang.reflect.Method.invoke(Method.java:597)
2012-11-20 11:47:18 STDIO [ERROR] at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
2012-11-20 11:47:18 STDIO [ERROR] at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:298)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.messaging.zmq.ZMQConnection.close(zmq.clj:43)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
2012-11-20 11:47:18 STDIO [ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
2012-11-20 11:47:18 STDIO [ERROR] at java.lang.reflect.Method.invoke(Method.java:597)
2012-11-20 11:47:18 STDIO [ERROR] at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
2012-11-20 11:47:18 STDIO [ERROR] at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:298)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.daemon.worker$mk_refresh_connections$this__5494.invoke(worker.clj:271)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.daemon.worker$mk_refresh_connections$this__5494.invoke(worker.clj:217)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.timer$schedule_recurring$this__1752.invoke(timer.clj:69)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.timer$mk_timer$fn__1735$fn__1736.invoke(timer.clj:33)
2012-11-20 11:47:18 STDIO [ERROR] at backtype.storm.timer$mk_timer$fn__1735.invoke(timer.clj:26)
2012-11-20 11:47:18 STDIO [ERROR] at clojure.lang.AFn.run(AFn.java:24)
2012-11-20 11:47:18 STDIO [ERROR] at java.lang.Thread.run(Thread.java:662)

Inside the sender thread (the crash happens exactly after the native "send" is invoked):

2012-11-20 11:47:22 STDIO [ERROR] java.lang.Exception: FATAL!!!  current: 0, old: 46912660098144
2012-11-20 11:47:22 STDIO [ERROR] at org.zeromq.ZMQ$Socket.send(ZMQ.java:871)
2012-11-20 11:47:22 STDIO [ERROR] at zilch.mq$send.invoke(mq.clj:93)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.messaging.zmq.ZMQConnection.send(zmq.clj:40)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn__5536$fn__5537.invoke(worker.clj:317)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn__5536.invoke(worker.clj:306)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.disruptor$clojure_handler$reify__1584.onEvent(disruptor.clj:43)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:79)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:55)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:56)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.disruptor$consume_loop_STAR_$fn__1596.invoke(disruptor.clj:67)
2012-11-20 11:47:22 STDIO [ERROR] at backtype.storm.util$async_loop$fn__465.invoke(util.clj:377)
2012-11-20 11:47:22 STDIO [ERROR] at clojure.lang.AFn.run(AFn.java:24)
2012-11-20 11:47:22 STDIO [ERROR] at java.lang.Thread.run(Thread.java:662)

Notice the "FATAL!!!   current: 0" statement, that means the "socketHandle" field becomes 0 when "send" is invoked.  Hence the abort in JZMQ.

**Comment by nathanmarz** [comment]
OK, well I'm going to close this pull request for now until we have an explanation for what really causes this crash.

**Pull request closed without merging**
