### PR TITLE
Help message per commands for Storm client

### PR DESCRIPTION
**Pull request by kachayev**
Updated `bin/storm`:
- usage message update
- help message per commands (e.g. `bin/storm help ui`) 
- simple error handling
- fix some Python misc

### CODE REVIEW

**Comment by nathanmarz** [comment]
This looks good. Before I can merge this in, I need you to send me a contributor agreement. More details here:

https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by kachayev** [comment]
Sent. Actually, I don't know if my signature is enough, but I can't find easy way to put my own one.

**Comment by nathanmarz** [comment]
HelloFax lets you draw your signature by clicking the "Add signature" button when editing the document. It would be great if you could resend it with an actual signature. Sorry for all the hassle!

**Comment by kachayev** [comment]
Resent. It was very interesting adventure :)

**Pull request merged**
