### PR TITLE
Do the worker HB timeout check when HB's are updated

### PR DESCRIPTION
**Pull request by d2r**
Instead of asking zookeeper for the latest heartbeat data for all topologies and then checking which heartbeats have timed out, combine the timeout check with the heartbeat update.

This makes nimbus more tolerant of a slow zookeeper server, in which case the updating of heartbeats can take so long that by the time the nimbus actually examines the new heartbeats for timeouts, most of the earliest topologies have complete timeouts of executors.

### CODE REVIEW

**Comment by d2r** [comment]
This pull request is initially intended to start discussion.

Current unit tests pass with this change.

**Comment by d2r** [comment]
This could mitigate a possible root cause for #689.

**Comment by brndnmtthws** [comment]
:+1: 

Good stuff.

**Comment by ptgoetz** [comment]
+1
(tested in distributed mode with 5-node cluster)

**Comment by nathanmarz** [comment]
+1

**Comment by xumingming** [comment]
+1

**Pull request merged**
