### PR TITLE
Fixes build_release.sh issue when using leiningen v2.3

### PR DESCRIPTION
**Pull request by jasonjckn**
latest version of leiningen breaks bin/build_release.sh creating zip without jar files. This fixes it by forcing lein to store jar in the same path it use to, target/... instead of target/profile-name/...

Steps to reproduce:
1. invoke bin/build_release.sh with leiningen version = 2.3.2+, you will see the zip file does not contain any jars.

### CODE REVIEW

**Comment by nathanmarz** [comment]
If it's backwards compatible let's take out the min-lein-version

**Comment by jasonjckn** [comment]
@nathanmarz Done. 

Tested on leiningen v2.3.2 and v2.2.0

**Comment by jasonjckn** [comment]
Fyi, my Author changed Author: Jason Jackson jackson@twitter.com 
Not sure if you care

**Comment by jasonjckn** [comment]
it's a pain in my setup to flip these back and forth.

**Comment by jasonjckn** [comment]
@nathanmarz I find the git history to be not so useful. 
commit cdbdf8dfc0719de5b6771a17bf4f3849cae3fe5f
Author: Jake Donham jdonham@twitter.com
Date:   Mon Aug 26 14:08:36 2013 -0700

```
oops
```

commit 85895c84ed28eb75ec6e5f7997cda74ce1bed61f
Author: Jake Donham jdonham@twitter.com
Date:   Mon Aug 26 14:07:01 2013 -0700

```
unique URLs in findAndReadConfigFile to work around apparent sbt/nsc bug where the same resource is returned more than once
```

commit 46cc0fcfcff077ede12cb14168db8fd11df8b227
Author: Jake Donham jdonham@twitter.com
Date:   Mon Aug 26 14:01:08 2013 -0700

```
make FixedTupleSpout implement IRichSpout so it can be used for tests
```

If you asked people to rebase their commits before merging it would clean this up.

**Pull request merged**
