### PR TITLE
Fixed issue 68

### PR DESCRIPTION
**Pull request by killme2008**
Fixed issue 68: use curator to handle zookeeper.

### CODE REVIEW

**Comment by killme2008** [comment]
All uni test cases passed successfully.

**Comment by killme2008** [comment]
Add a new option "ui.context.path",it is "/" by default.

I have to access storm ui by a context path such as "http://host:8080/storm-ui",then i can set ui.context.path: "/storm-ui" to get it done.

**Comment by killme2008** [comment]
I've run this patch on my storm cluster for one week now,it seems all is fine.

**Comment by nathanmarz** [comment]
What's the point of the ui context path stuff? This is unrelated to using curator for zookeeper and should be discussed separately.

**Comment by killme2008** [comment]
I am sorry.It seems that github will add all commits to the pull requests.The patch is only 

https://github.com/killme2008/storm/commit/37665fd19df98f66096b36b07eae89fcf1debb86
and:
https://github.com/killme2008/storm/commit/d891c79c6c8ba7ec65f6524f573ee0c6ec60e061

The ui.context.path option is only useful for us,we have a system to manage all system's web console,and it need a conext path for authority and dispatching.

**Comment by nathanmarz** [comment]
OK, I'm close to being able to merge this stuff in. One question: why do you call isStarted before calling close?

**Comment by killme2008** [comment]
When I didn't call isStarted  method before close, some unit test cases failed because of closing curator more than once.Curactor doesn't allow calling close method more than once.And it seems that some unit test cases do it.So i have to check if the curator client is started before closing it.

**Comment by nathanmarz** [comment]
I merged in those two commits with a couple modifications. Thanks for the patch!

**Pull request closed without merging**
