### PR TITLE
Clears up a lot of confusing nomenclature.

### PR DESCRIPTION
**Pull request by moonpolysoft**
Bolth.

### CODE REVIEW

**Comment by reinsphone** [comment]
:+1:

**Comment by ieure** [comment]
I'm -1 on this, due to the impact it has on Storm naming conventions. Storm uses StudlyCaps (`CoordinatedBolth`), rather than Uppercase (`Coordinatedbolth`).

I'm +1 if the patch is updated to be consistent with the existing conventions.

**Comment by nathanmarz** [comment]
You'll need to sign a contributroll agreement before I can merge this in

**Comment by KirinDave** [comment]
This is quality internet.

**Comment by xumingming** [comment]
Why change bolt to bolth?

**Pull request closed without merging**
