### PR TITLE
Storm UI: take nimbus host from the conf

### PR DESCRIPTION
**Pull request by Frostman**
Hostname of Nimbus should be taken from conf files instead of hardcoded "localhost".

### CODE REVIEW

**Comment by nathanmarz** [comment]
I'll need you submit a contributor agreement in order to look at this. Should only take a few minutes. Instructions here: https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by Frostman** [comment]
I sent you a contributor agreement.

P.S. I think that information about the need to sign contributors agreement can be added after the list of contributors in main project's README to increase its visibility.

**Comment by nathanmarz** [comment]
Thanks, merged!

**Comment by Frostman** [comment]
Thank you!

**Pull request merged**
