### PR TITLE
Implemented the ShellSpout class to allow us to write multi-lang ShellSpouts

### PR DESCRIPTION
**Pull request by jimrubenstein**
Nathan, I used the multi-lang protocol wiki page, and the ShellBolt class to build out this class to implement ShellSpouts.

Let me know if there's something major missing, or it's missing something I can implement.

Cheers,

Jim

### CODE REVIEW

**Comment by nathanmarz** [comment]
Thanks for implementing this. I just got a chance to look at it right now, and there's a few things needed for me to merge this in:
1. Spout needs to send the return of "emit" back to the subprocess. Check out how ShellBolt does this -- it's a one-liner.
2. Should implement either the python or ruby side of the protocol so that it can be tested (I'll take care of writing the unit test).

**Comment by jimrubenstein** [comment]
Sure, I can take care of adding those two things.  I'll do that and then push to this pull request once I have it done.

Thanks for having a look, and the feedback!

**Comment by jimrubenstein** [comment]
So, at the risk of sounding like a complete noob...let me just say that one of these commits include a delete of the bin directory...i did that because i was recompiling storm to test the changes with the shell spout.  My intention was to never have those pushed to github - but the totally awesome Github for Mac client screwed me and committed changes on it's own or something.

Anyway, I hope you can easily cherry pick those revs out of this...if not, I can try to do some magic and resubmit the pull request or something.  Github doesn't seem to like when you try to change history (I tried to fixup those commits, but it yelled at me when I tried to push).

In any case, I did write an implementation of the ShellSpout for python (I started working on the ruby one also, but I write ruby less often than python, so I thought I'd either let someone else do it, or just go a little slower so I can test it better).  I also updated the ShellSpout.java class to return the tasks that the tuple was emitted to back to the ShellSpout.

Sorry for the hassle...I guess I just suck at github ):

**Comment by nathanmarz** [comment]
OK, I tried to take a look at this and there's a lot of noise in these commits. Can you make a new pull request with only the relevant changes? Sorry for the delay in responding, but I do really want to get this stuff merged in.

**Comment by jimrubenstein** [comment]
Yeah, I'll close this pull request and start a new one with all the changes squashed in.

**Pull request closed without merging**
