### PR TITLE
Include a warning about Leiningen 2.x in docs

### PR DESCRIPTION
**Pull request by gsilk**
Currently "lein (uber)jar" silently fails when using lein >= 2, and "lein test" complains about missing files on the classpath.

This is a pain when you're trying to get your dev environment setup for Storm, after following every instruction to a tee, only to have nothing work. As long as Storm is incompatible with lein 2.x, a big warning should be included somewhere in the docs telling the user to use lein 1.x

### CODE REVIEW

**Comment by nathanmarz** [comment]
You're referring to compiling Storm itself? The 0.9.0 branch is upgraded to lein2.

**Comment by gsilk** [comment]
Still, it would be good to have a warning in place until 0.9.0 is merged into master. New contributors will do their work off of master, and currently, if they go and download leiningen and start trying to contribute, _nothing_ will work (and there won't be any sensible errors describing why). That's a great way to give all your newcomers a migraine. Just sayin'.

**Comment by nathanmarz** [comment]
Fair enough. Is there a way to set a required lein version flag in the project.clj?

**Comment by gsilk** [comment]
Dug around and found that Leiningen exports its version into the environment. Code attached.

**Comment by gsilk** [comment]
I also looked at what was available in defproject -- unfortunately lein only supports a minimum version check.

**Comment by nathanmarz** [comment]
Merged, thanks. BTW, in the future you should put your pull request in its own branch (not master) so that you can keep it isolated from any other changes you want to make.

**Pull request merged**
