### PR TITLE
Fix ClassCastException (was: logs a warning if we fail to delete a file)

### PR DESCRIPTION
**Pull request by d2r**
prevents ClassCastException

### CODE REVIEW

**Comment by d2r** [comment]
Saw this on a file permission error.

We may want to throw a RuntimeException here instead?

**Comment by revans2** [comment]
I don't think we want to throw a RuntimeException.  That would bring down nimbus, and because the file permissions were not fixed it would just crash again the next time it came up.  Because it is only cleaning up the files logging the error I think is enough.

**Comment by nathanmarz** [comment]
-1. It's definitely an error and an indication that something is wrong with the setup.

**Comment by d2r** [comment]
OK, so do we want to call log-error correctly then, since it expects a Throwable as the first argument (not a String)?

**Pull request closed without merging**
