### PR TITLE
original conf file #243.

### PR DESCRIPTION
**Pull request by tjun**
for #243.
Added -conffile option to use original yaml file.

> storm jar allmycode.jar -conffile org.yaml org.me.MyTopology arg1 arg2 arg3
> ( Conf filename must be written in relative path from ~/.storm/)

Also added -confdir option to use orignal confdir, instead of ~/.storm .

### CODE REVIEW

**Comment by nathanmarz** [comment]
Sorry for the really late response to this. Can you send me a contributor agreement so that we can iterate on this? Instructions here: https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by tjun** [comment]
Thank you for your response. I think I had sent you the document. The mail was sent on Feb.9.
Should I  resend it?

**Comment by nathanmarz** [comment]
You're right! I found it, and it looks good.

I'm not a fan of this implementation. I think we can make things substantially simpler.

I don't think there's any reason to make the conf dir configurable – we should just make the conf file configurable via the --config option. Here's what I propose:
1. In parse_config_opts, set a global variable called "CONFFILE" to the value of that option.
2. In exec_storm_class, set -Dstorm.conf.file option to the value of that global var.
3. In backtype.storm.utils.Utils#readStormConfig look for that environment variable. If it's set, use that filename. If it's not set, use the string "storm.yaml".

**Comment by tjun** [comment]
Sorry for a lot of commits. 
I fixed code, so pick the last commit: 5cf1d90 please.

**Comment by nathanmarz** [comment]
Thanks! I merged in that commit.

**Pull request closed without merging**
