### PR TITLE
More detailed error messages when the shell subprocess pipe closes.

### PR DESCRIPTION
**Pull request by vinodc**
I've added any ouput from the error stream of the subprocess to the detail message of the RuntimeException thrown to make it easier to figure out why the subprocess exited unexpectedly.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Great idea. Can you send me a contributor agreement so I can merge this in? Instructions here (should only take a few minutes): https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by vinodc** [comment]
Sure. Sent you the agreement.

**Comment by nathanmarz** [comment]
Thanks. This patch is going to make debugging multilang issues infinitely easier. I also made it so the error stream is captured and printed if the subprocess fails to launch.

**Comment by vinodc** [comment]
Oh good idea. Yeah, it's been helpful during debugging.

**Pull request merged**
