### PR TITLE
Use 'equals()' method to String comparison instead '=='

### PR DESCRIPTION
**Pull request by miofthena**
Fix local cluster mode RuntimeException

### CODE REVIEW

**Comment by xumingming** [comment]
+1

**Comment by ptgoetz** [comment]
+1

Added to 0.9.0 milestone.

@miofthena have you filled out a contributor license agreement?

**Comment by miofthena** [comment]
@ptgoetz , I have sent the contributor agreement to @nathanmarz

**Comment by nathanmarz** [comment]
+1, and confirming that I've received the contributor agreement

**Comment by nathanmarz** [comment]
Taylor – this is a pretty simple pull request, but let's stick to the rule of leaving pull requests open for 3 days before merging so that all committers have a chance to weigh in.

**Pull request merged**
