### PR TITLE
make FixedBatchSpout batch aware.

### PR DESCRIPTION
**Pull request by ptgoetz**
Minor update to make `storm.trident.testing.FixedBatchSpout` handle batches properly (useful for unit testing batch failure).

Without this fix, in the event of a failed batch, the spout will emit a new batch with potentially different content.

### CODE REVIEW

**Comment by nathanmarz** [comment]
This looks good overall, though can you change the ConcurrentHashMap to be a regular HashMap? All this code runs on the same thread.

**Comment by ptgoetz** [comment]
Sure. Sorry for the delay -- I lost track of this pull request.

**Comment by ptgoetz** [comment]
Done.

**Comment by ptgoetz** [comment]
Ported to new multi-module directory structure. Should merge cleanly now.

**Pull request merged**
