### PR TITLE
implemented the command: 'storm list'

### PR DESCRIPTION
**Pull request by xumingming**
for issue #166

### CODE REVIEW

**Comment by nathanmarz** [comment]
Merged. Thanks for the great patch!

**Comment by nathanmarz** [comment]
Actually, before I can release your patches I'm going to need you to sign a contributor agreement. Should only take you a couple minutes, and you can find instructions for that on the bottom of this wiki page: https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by xumingming** [comment]
Sent the agreement.

**Comment by nathanmarz** [comment]
Got it, thanks.

**Pull request merged**
