### PR TITLE
Update to Curator 1.1.3/ZooKeeper 3.4.x

### PR DESCRIPTION
**Pull request by ashleywbrown**
Replaces the Curator 1.0.x series dependency with 1.1.3, which introduces ZooKeeper 3.4.2. Changed the in-process ZK server to use the new NIOServerCnxnFactory in ZooKeeper 3.4.x.

ZK 3.4.x clients are compatible with ZK 3.3.x ensembles.

This change makes Storm compatible with HBase 0.92, which requires the new ZK 3.4 API.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Can you send me a contributor agreement so I can merge this in? Instructions at the bottom of this page (should only take a couple minutes): https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by ashleywbrown** [comment]
Yep, with you shortly.

On 18 May 2012 20:02, Nathan Marz <
reply@reply.github.com

**Comment by nathanmarz** [comment]
Merged, thanks!

**Comment by nathanmarz** [comment]
@ashleywbrown I had to revert this because the new Curator client has a major performance regression. The startup of the client takes a considerable amount of time, making the Storm tests take way longer.

**Comment by ashleywbrown** [comment]
No problem. Hopefully they'll fix it soon!

**Comment by tomdz** [comment]
Any chance that only the Zookeeper portion of this could be applied ? Also, curator is at 1.2.5 now, maybe they fixed the performance regression ?

**Comment by jasonjckn** [comment]
I attempted to upgrade storm to zk 3.4.5, and it caused a unit test regression transactional-test non-determinstically hangs.

**Pull request merged**
