### PR TITLE
add web ui for :

### PR DESCRIPTION
**Pull request by xiaokang**
1. viewing log file
2. get/set log4j log level online

### CODE REVIEW

**Comment by xiaokang** [comment]
for issuse #543

**Comment by nathanmarz** [comment]
What happens to the supervisor if something goes wrong with the internal log UI? What if the string being returned is 1GB in size, for example? We need to make sure that these edge conditions are accounted for, or that the supervisor crashes with an exception whenever they happen.

**Comment by xiaokang** [comment]
Hi nathan, thanks for review.

If something goes wrong (such as log file does not exist) with the log UI, an exception message will be logged by Jetty.

The code limit the string returned to 10000 lines and 10MB by reading n (default 1000, max 10000) lines from the read point (file length - tail length(deault 10KB, max 10MB)) of the logfile. A very extreme edge condition that the log file grows very fast and a single line starting from the read point is larger than 10MB will cause large memory consumption.

**Comment by nathanmarz** [comment]
Yea, let's remove the logic around number of lines and only read form the file in terms of number of bytes. That way we can just set an upper limit to how much can be returned and protect against any memory issues.

**Comment by xiaokang** [comment]
OK, I will try to implement this and update the pull request.

**Comment by nathanmarz** [comment]
Actually, on second thought – can we just make this its own independent daemon process? Isolating it from the supervisor process ensures something going wrong in the log viewer won't affect the supervisor (or is at least much less likely to).

**Comment by xiaokang** [comment]
Isolating it from the supervisor process is indeed more safe for supervisor but it's more complicated to deploy a storm cluster. So it may be balance between easy to use and very rare errors. 

It should be safe to integrate it in supervisor since viewing web UI log is usually issued by by human not so frequently.I have made some change to the code to ensure that only read some byte (default 10KB, max 10MB) from tail of log file. Hope that it will be more acceptable since our users feed back that web UI for logs is really useful.

**Comment by nathanmarz** [comment]
I thought about it more and this really should be done as its own daemon. It barely makes things more complicated, It's just another process that needs to be daemonized. In almost all setups this should be a one line deployment change. Isolation of functionality is always worth it when the cost of doing so is so low. Let's go ahead and add a log viewer daemon to backtype.storm.daemon and add the appropriate command to the bin/storm script to launch it.

**Comment by xiaokang** [comment]
OK, I agree with that it's worth to doing so for isolation and system stability. I will update the code soon.

**Comment by xiaokang** [comment]
Just updated the code.

**Pull request merged**
