### PR TITLE
kill --all flag

### PR DESCRIPTION
**Pull request by Frostman**
Simple way to kill all topologies in Storm cluster.

build: http://f.frostman.ru/tsc-dists/storm-0.8.2-wip15-killall.zip

### CODE REVIEW

**Comment by nathanmarz** [comment]
I don't think this is important to have as a core feature in Storm. If people want to do this they can write their own scripts for it.

**Comment by Frostman** [comment]
I thought it was great to have additional facilities out of the box. I'm sorry to bother you.

**Comment by nathanmarz** [comment]
No it's fine, but sometimes I have to reject features that I think aren't useful enough to be in the core project. I always welcome new ideas.

**Comment by tas50** [comment]
I'd argue that this is a code change worth doing. We maintain a publicly available Chef recipe to deploy Storm at my company.  It would be very nice to be able to kill all running topologies as part of the deploy process.  Without this we can't fully automate the process of deploying storm.  We have added our own code to kill our specific topology, but this isn't something that can be contributed to the greater community.  I imagine that anyone trying to automate deploys of storm using either Puppet or Chef would run into a similar problem.

**Pull request closed without merging**
