### PR TITLE
fix issue with shell bolts not restarting

### PR DESCRIPTION
**Pull request by tomjack**
Since exceptions (e.g. when the shell process crashes) are thrown in new threads now, the ShellBolt keeps on running.

Does this patch fix all such issues?

### CODE REVIEW

**Comment by nathanmarz** [comment]
Good catch. I tweaked it a little, mainly generalizing it to set _exception for any Throwable, not just IOException

**Comment by hellp** [comment]
Thanks for the quick fix and merge. I was just testing it on our system. Works fine :)

**Comment by tomjack** [comment]
I considered changing it to Throwable, but wouldn't this inappropriately catch e.g. OOM errors? Is that not a problem because the Error will just get thrown again at the beginning of execute?

Also I'll note that hellp alerted me to this problem, I only quickly provided the fix :)

**Comment by nathanmarz** [comment]
Yea, it's fine because it will just get rethrown. It's important that any problem with those threads causes the worker to crash.

**Pull request merged**
