### PR TITLE
fix for issuse 122

### PR DESCRIPTION
**Pull request by xiaokang**
Only commit 1f63ad98 is needed. I am sorry that I can not produce a pull request just contains the commit.

### CODE REVIEW

**Comment by xiaokang** [comment]
hi nathan, how about this pull request? Is there any more work needed?

**Comment by nathanmarz** [comment]
Hey, now that 0.7.0 is out the door I'm going to start merging in some of these pull requests. I'll let you know when I take a deeper look at this.

**Comment by nathanmarz** [comment]
@xiaokang I'm ready to merge this in. Can you sign a contributor agreement? (follow the directions here https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm )

**Comment by xiaokang** [comment]
@nathanmarz I have sent the signed agreement to you. Thanks for your advice of using HelloFax. It is easy to use and really useful!

**Comment by nathanmarz** [comment]
@xiaokang Hmm, I actually didn't receive it. Could you try sending it to me again?

**Comment by nathanmarz** [comment]
Merged to master.

**Comment by xiaokang** [comment]
@nathanmarz I'm sorry it was in on hold status. Now I resend it and it is in sent status. You can check it.

**Pull request closed without merging**
