### PR TITLE
Fix netty transport unit tests

### PR DESCRIPTION
**Pull request by ptgoetz**
Unit tests were failing because they did not define values for the number of client/server worker threads.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Should there just be defaults for those configs in defaults.yaml?

**Comment by ptgoetz** [comment]
Values are there in `defaults.yaml`, but the netty transport tests use hard-coded config values rather than read from that file.

**Comment by nathanmarz** [comment]
Oh I see. Cool, +1

**Comment by xumingming** [comment]
+1

**Pull request merged**
