### PR TITLE
resolved the issue that when a topology has not been assigned a task, the storm-ui breaks

### PR DESCRIPTION
**Pull request by xumingming**
for issue #92

### CODE REVIEW

**Comment by nathanmarz** [comment]
I tried this out and it didn't fix the problem.

**Comment by xumingming** [comment]
the page still breaks? i did tested and the page didnt break, and sections: **Topology stats**, **Spouts (All time)**, **Bolts (All time)** remains empty.

**Comment by xumingming** [comment]
Nathan, the screenshot below is how a no-task-assigned-topology looks like in storm UI after my fixing, it is what we expected, right? 

storm-ui screenshot

**Comment by nathanmarz** [comment]
Yea actually I tested it wrong. I'll test again tomorrow and then merge.

**Comment by nathanmarz** [comment]
Yea this works fine :)

**Pull request merged**
