### PR TITLE
URLEncoder for ui.core (issue 122 )

### PR DESCRIPTION
**Pull request by tjun**
This patch fix issue #122
Add URLEncoder for ui.core to use space character in spout/bolt id.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Thanks! I need you to sign a contributor agreement before I can merge this in. Instructions here:

https://github.com/nathanmarz/storm/wiki/Contributing-to-Storm

**Comment by tjun** [comment]
Sure. I signed and sended it.

**Comment by xiaokang** [comment]
Thanks for Pull Request #128. But it can not fix issuse 122 completly since it just fixes one occurence of format function. So I send a pull request #133 to fix this issuse.

**Comment by tjun** [comment]
Great, thanks!

**Pull request closed without merging**
