### PR TITLE
Platform jar

### PR DESCRIPTION
**Pull request by xumingming**
For Issue #281

### CODE REVIEW

**Comment by xumingming** [comment]
@nathanmarz How about this one?

**Comment by xumingming** [comment]
@nathanmarz any comments? if not right, I'd close it.

**Comment by nathanmarz** [comment]
I'm still thinking about this issue. Once 0.8.2 is out I'll come back to this.

**Comment by nathanmarz** [comment]
Going to close this, as its only relevant to standalone Storm clusters, and non-standalone clusters would need a completely different solution. Thanks for implementing this though – and sorry for changing my mind on the feature.

**Pull request closed without merging**
